### PR TITLE
Add dotnetcore project

### PR DESCRIPTION
**Pull request by christopherbahr**
This introduces another project to build the code for dotnetcore on the netstandard1.5 APIs which will allow this library to be referenced in other dotnetcore libraries and to be run cross platform.

This code is all nearly identical to the PCL code with some tiny tweaks to some reflection code to work on the new APIs.

The unit tests won't integrate with the Visual Studio test runner at the moment so they have to be run from the console using `dotnet run` or by setting the tests project as the startup project and running from visual studio.

To work in VS it does require VS 2015 but it can be built from the command line using `dotnet build`.

### CODE REVIEW

**Comment by MaxPresman** [comment]
@christopherbahr,

Thanks for the PR! We are currently working on a similar effort at this [branch](https://github.com/pubnub/c-sharp/tree/ppt120693699/NetPlatform). We are investigating a try to integrate the new platform into the existing build set, but if it's not possible, we will release it as a new target.

**Comment by christopherbahr** [comment]
Oh great that you're already working on it! Do you have an ETA on when a NuGet package will be available? Is there anything I can do to help push that forward?

**Comment by MaxPresman** [comment]
@christopherbahr we are hoping for a first preview by the end of next week, be sure to star the repo and we will send out updates once it landed : )

**Comment by MaxPresman** [comment]
@christopherbahr, we have created a pre-release version (for RC .net) avaliable on the `dotnetcore_ppt120693699` branch, please give it a pilot run.

**Comment by christopherbahr** [comment]
I had some trouble getting the WPA81 build to work but I dropped that and built for netstandard1.3 (you guys have netstandard 1.5 but it doesn't seem like you actually need it) and installed the nupkg file into my solution and all of my integration tests pass. So at a first look at least everything seems fine :+1: 

I'd recommend going to netstandard 1.3 because then anyone targeting .NET 4.6 will be able to use that version without any issues. Plus your build works just fine with that so you shouldn't need to change anything.

**Comment by marchy** [comment]
Any updates on this now that [.NET Core RTM](Any updates on this now that .NET Core RTM has been out? (for 3 weeks now)) has been out? (for 3 weeks now)

Thanks!

**Comment by MaxPresman** [comment]
@marchy / @christopherbahr we are working towards adding a .net target into the published SDK; we hope to release it in the next few coming days.

**Comment by alexidsa** [comment]
Has that branch been integrated into master? I'm trying to use Pubnub library in netcoreapp1.1 and it is not working...

**Comment by budgetpreneur** [comment]
Yes. 3.x version is available at master. https://github.com/pubnub/c-sharp/tree/master/NetPlatform.
You can get nuget package at https://www.nuget.org/packages/PubnubNetPlatform/

**Comment by alexidsa** [comment]
It would be great if readme file was clear about what packages should be used for different platforms. I was trying to install Pubnub package and it didn't work out. By the way, do I get it right that v4 rc is not available for .NET Platform?

**Comment by budgetpreneur** [comment]
For V4 SDK, check this out https://www.pubnub.com/docs/dot-net/pubnub-c-sharp-sdk-v4

**Comment by alexidsa** [comment]
Current Nuget packages naming seems chaotic. Like I had to use PubnubPcl library for my ASP.NET Core application. And moreover, when I go to package web page at nuget.org, it says this package is deprecated. It's extremely confusing.

**Comment by budgetpreneur** [comment]
Please send email to support@pubnub.com with what you are looking for and we will happy to guide you.

**Comment by alexidsa** [comment]
I wrote to this email but never got response.

I'm porting my application from SignalR to Pubnub and I see a lot of problems with v4 codebase (bugs, poor design, etc.). I'd really like to have a more efficient communication channel than email. It's a pity you guys disabled Issues on GitHub: it makes issues/workarounds/solutions being shared among community, not hidden inside your email box.

**Pull request closed without merging**
