### PR TITLE
C# v4.21.1 SDK Release

### PR DESCRIPTION
**Pull request by parfeon**
**Release include following changes:**
* ⭐️ Increase message count default limit for History v3 api call to 100 for single channel.

### CODE REVIEW

**Review by budgetpreneur — CHANGES_REQUESTED** [review]
Our last version is C# V4 SDK 4.12.0.0.
So next version should be 4.13.0.0 for consistency.
Also merge should happen ONLY when nuget packages are ready for published.

**Comment by parfeon** [comment]
@budgetpreneur it is me messed up with branch name. 

Codebase goes for `v4.12.1`. Will it be ok to pass it like this, because branch still will be removed after merge?

**Comment by budgetpreneur** [comment]
> @budgetpreneur it is me messed up with branch name.
> 
> Codebase goes for `v4.12.1`. Will it be ok to pass it like this, because branch still will be removed after merge?

Visual Studio project files needs to be updated with version number for nuget packages creation. so we need to update before we merge to master.

**Comment by parfeon** [comment]
ah, some more work for @mohitpubnub

**Comment by budgetpreneur** [comment]
> ah, some more work for @mohitpubnub

yeah....little work needed before pushing it to customer

**Comment by mohitpubnub** [comment]
> > ah, some more work for @mohitpubnub
> 
> yeah....little work needed before pushing it to customer

On it!!!
@budgetpreneur Thanks for reminding

**Pull request closed without merging**
