### PR TITLE
handle serialization of JArray type messages

### PR DESCRIPTION
**Pull request by defrobo**
I found a parsing exception was being thrown when the message content was a JSON array. I changed the internals of NewtonsoftJsonDotNet to serialize out JArray types specifically.

I added a Unit Test for this, I couldn't find any tests to cover the NewtonsoftJsonDotNet class.

I also had to add a NET35 compilation symbol to the Unit Tests project; the json parsing code is wrapped in conditional compiler directives.

### CODE REVIEW

**Comment by budgetpreneur** [comment]
@defrobo  Thank you for contacting us. By design we are not doing it.
When the user subscribes like pubnub.Subscribe<string>(), pubnub sdk expects the users to publish string type messages but not the complex message you showed in example. If you are sending complex message like you showed in your example, all you have to do it subscribe for "object" type like pubnub.Subscribe< object >() and this should avoid the JSON parse errors you experienced.

**Comment by defrobo** [comment]
@budgetpreneur thanks for checking the PR. I take your point about the pubnub SDK expecting string type messages.

I'm writing a client app that consumes a realtime feed exposed over pubnub, so I don't have any control over what the publisher sends. But I'll try your suggestion.

```
                else if (listObject[0].GetType() == typeof(Newtonsoft.Json.Linq.JArray))
                {
                    JToken token = listObject[0] as JToken;
                    userMessage = token.ToObject(dataProp.PropertyType, JsonSerializer.Create());

```

Just wondering though, if the listObject[0] has been inspected as a JArray, why would you cast it as JToken? If you do this, won't the call to token.ToObject() always throw a parsing exception?

**Comment by budgetpreneur** [comment]
token.ToObject() should not throw parse exception for JArray because JToken is abstract base class of JArray.
If your message type is not known while subscribing, please use pubnub.Subscribe< object>(). Once your subscribe listener receives the object, you can cast it to your known object type or serialize it to string as you wish. For any further assistance, please reach out to support@pubnub.com

**Comment by defrobo** [comment]
Thanks for the explanation. I'll close this PR now.

**Pull request closed without merging**
