### PR TITLE
DeNA Vancouver Various fixes

### PR DESCRIPTION
**Pull request by samuelcadieux**
These changes include simple changes such as adding meta files, removing generated files, adding proper gitignores, marking cs files a non-binary files, fixing file encoding. And later functional changes such as not silently failing messages or switching from .NET WebRequests to unity's WWW class depending on the content of the message (one need to run in a separate thread while the other needs to run on the main thread).

Also I highly suggest that you create a unity branch since unity has this specific structures it makes it hard to import this project as a submodule. And then I would add the unity branch as a submodule into master or a subtree. I'm doing the later on my repo.

Cheers!

### CODE REVIEW

**Comment by geremyCohen** [comment]
@samuelcadieux thanks for the contribution! We're currently working on an official Unity 5 compatible port, we'll fold these suggestions into that codebase as soon as its completed and backport as needed as well.

**Comment by crimsonred** [comment]
@samuelcadieux, thanks for the pull request. As you now we have been working on a new version (https://github.com/pubnub/c-sharp/tree/pt87102862/unity5) and in that version we have modified the code to use Unity's www class for networking. A lot has been modified in the new code. I have reviewed your each commit and have used some of your code. There are some questions as well:

Questions:
* Fixing unity example scene, aef3ecc: can you please explain what was fixed?
* Removing binary flag on c# files, 59ccda9: we don't have binary flag on the cs file, was this for your repo?
* Fixing encoding, d129c21: can you please give us the details for this. Is this related to d4e180f?


Others commits:
* Fixing buid error when JSONFX is not present, 97102a7: This file has been removed from the new version
* Fixing compilation warnings, 838be23: This file has been removed from the new version
* Removing generated files and adding proper git ignore for unity projects, eca530b: retaining /Library/, .sou, .sln as we have other c# projects in the repo.
* Moving Pubnub unity scripts files to a proper folder to facilitate su… …, 855614a: Moved to scripts folder as per your suggestion, yet to commit
* Moving Pubnub unity scripts files to a proper folder to facilitate su… …, 78283d0: Moved to scripts folder as per your suggestion, yet to commit
* Adding proper ignore file to unity branch, 20a5111: added
* Preparing master for bringing unity subtree, 5aea877: planning to move Unity to a new repo, github.com/pubnub/unity. Under this repo we will have the code for C# and UnityScript. Will create subrtree.
* Cleaning up temporary object created when publishing a message, 868278a: fixed in new version
* Throwing an execption in case of an invalid request, ff9d0ff: this functionality has been removed from the current version. We have used Unity's www class all around now.
* Removing . from unsafe characters, d4e180f: The RequestIsUnsafe is used to urlencode some chars, we would like to retain '.', '<' and '>'. 
* Fixing an issue where pubnub would try to read an array as a dictionary, ad2c039: Fixed as per your suggestion
*Adding a workaround where pubnub would silently kill existing request… …, e98968d: In all our SDKs we 'abort' the existing requests before initiating a new request of the same 'type'. A callback is fired when this happens. 
* Making Pubnub's hearbeat messages unable to cancel user messages, 79864aa: Heartbeats are handled separately in the new version
* Putting pubnub's heartbeats in their own queue, 1982881: Heartbeats are handled separately in the new version
* Updating unity subtree's, f7ec714: TODO

**Comment by samuelcadieux** [comment]
Good Morning!

Good to hear! As of your questions here are my response:

   - Fixing unity example scene, aef3ecc
   <https://github.com/pubnub/c-sharp/commit/aef3eccf4caba520b3b04513f880e851b00c35bd>:
   can you please explain what was fixed?
   Nothing big just missing reference to the monobehavior
   - Removing binary flag on c# files, 59ccda9
   <https://github.com/pubnub/c-sharp/commit/59ccda94385cb5b505fe0043498ca12556b9fac6>:
   we don't have binary flag on the cs file, was this for your repo?
   As you can see I was unable to do diff on the files since git believed
   the files were binary so I was trying to solve this issue. Not sure if it
   worked. Also I was unable to use git grep -- *.cs since the files were
   binary.
   - Fixing encoding, d129c21
   <https://github.com/pubnub/c-sharp/commit/d129c21ef3a5895665ec277439cecd3a60c78aea>:
   can you please give us the details for this. Is this related to d4e180f
   <https://github.com/pubnub/c-sharp/commit/d4e180f997678ed9fe67c2da16e2482e05b38061>
   ?
   That was included in my attemps to fix the binary files, one of my
   theory was that it was related with some files being encoded in UTF-16

As of:

   - Removing generated files and adding proper git ignore for unity
   projects, eca530b
   <https://github.com/pubnub/c-sharp/commit/eca530bed787ce08224480fb6224b3bea363fa63>:
   retaining /Library/, .sou, .sln as we have other c# projects in the repo.
   I was assuming that the root "/" for the git ignore file was the
   directory in which the ignore file was placed no?

**Comment by crimsonred** [comment]
@samuelcadieux Good Morning,

Thanks for the answers.

"That was included in my attemps to fix the binary files, one of my theory was that it was related with some files being encoded in UTF-16", 
[RK] yes one of the file was encoded UTF-16 on purpose. This was the unit test for Emojis. I don't see github marking .cs files as binary in the new code.

"Removing generated files and adding proper git ignore for unity projects"
[RK] you are right that the root "/" for the git ignore file was the directory in which the ignore file was placed. I will add the .gitignore to exclude .sou and .sln for the folder. But will retain some files from the Library folder, if I remove this the links between the Integration tests and the test case files disappear.

**Pull request closed without merging**
