### PR TITLE
C# v4.13.0 SDK Release

### PR DESCRIPTION
**Pull request by parfeon**
**Release include following changes:**
* ⭐️ Increase message count default limit for History v3 api call to 100 for single channel.
* 🐛 UnsubscribeAll fix when no channels subscribed.

### CODE REVIEW

**Comment by mohitpubnub** [comment]
@budgetpreneur  let us know about nuget publish stuff sync things!

**Review by mohitpubnub — APPROVED** [review]

**Comment by budgetpreneur** [comment]
nuget packages were published at nuget.org.

**Review by budgetpreneur — APPROVED** [review]
LGTM

**Comment by budgetpreneur** [comment]
@parfeon changes were approved, but still "Merging is blocked". Who can merge to master?

**Comment by mohitpubnub** [comment]
I think He is authorized person here to merge!

**Comment by budgetpreneur** [comment]
Then only @MessagingMoore can do this merge to master. Please escalate this to @MessagingMoore

**Pull request merged**
